### ISSUE TITLE
Crear magstats step

### ISSUE THREAD

**Issue by ASHuenchuleo** [alercebroker/magstats_step#1]
```[tasklist]
### Tasks
- [x] Crear step nuevo con la estructura necesaria
- [x] Implementar do_magstats
- [ ] Calcular todas las propiedades del objeto
- [x] Producir mensaje de scribe en tópico w_object
```

# Criterio de aceptación

- Generar mensajes de scribe en w_object
- Mensajes incluyen todas las propiedades del objeto que están en DB Plugins, exceptuando las propiedades que se calculan en los otros pasos, como probabilities y features.

# Requerimientos
- Mensajes de curva de luz, generados por el lightcurve step
